### ISSUE TITLE
Escort Kill Proof

### ISSUE THREAD

**Issue by Friteusenfett** [m10x/Gw2ChatCodeBuddy#1]
The Escort kp might be confusing for the players because its not the item you get dropped from McLeod. I'd consider to use this one as killproof [&AgEZNAEA]

**Comment by Friteusenfett** [comment]
Also the programm says "Write 1-12 to assign a chatcode to F1-F12" But you can only use F1-F11

**Comment by m10x** [comment]
Thank you for your Feedback, I appreciate it. When I'm back at home tonight I'm gonna change the typo and look into the escort kp. :)

**Comment by m10x** [comment]
I wanted to enable F12 also as hotkey but for some reason I couldn't find out yet, the program crashes than, so I disabled f12 again

**Comment by m10x** [comment]
I considered your feedback, new version will be online in few minutes 👍
