### ISSUE TITLE
Fakers thank you

### ISSUE THREAD

**Issue by DoctorD90** [m10x/Gw2ChatCodeBuddy#2]
Dear devs,
this isnt an elitist opened "issue", just the experience from a raid player, that after some raid, will never approve this sort of stuff :)
I started some month ago to do raid with 0 LI, as all player in gw2. I didnt know about raid. I hadnt LI. I havent experiences in raid.
I experimented on my skin that many players are elitist with no reasons. Some commander asks for 250li when he just started raid and probably has 10li.... Ok i totally agree that many people like to be carried.
Starting from this point, I really would ask you to insert a line, a reference to your program in "chat text" for an easy reason.
Me, as any other gw2 player, has started with 0LI, and now, I have (atm) 150li more or less.
When I m accepted in 250li raid group, they sometimes speak about complicated strategy, that only "skilled" player with some experience could accomplish. Kill the boss 1 time, gives people the knowledge of what it is there in raid. Kill a bunch of time, gives the knowledge of what to do with THAT PRECISE class (a tanker or a druid or a dps has very different role many times). Kill a boss with a druid, will not give "the knowledge" to tank at 2nd time. I agree with you that keep kill proof is a waste of invetory space; I put them in guild. When I join in squad, i say "hi! I have X li, my available classes for this raid are, and I havent kp (if required) cause i put them in guild. I have killed the boss Y/many times. Could I stay?".....some stupid elitist kicks me. Other just says "no", other gives "ok, 1 try. Fail=kick". I dont fail, and I will get the raid. I did in this way (as many other player) and from 0 i raise to +150li. It is a little hard but i did it, and im not the only 1 in the game.
Game doesnt provide any possible way to "test" the knowledge of a raid. Only linking the LI or KP. It is there no difference between a 120li and a 150li (more or less...2 weeks of raid)...so "fake" li with your program in that case is very useless. Fake LI is much more comfortable in cases like "i have 0li, I join 250li squad, and i will got carried". This would mean that people that wasted their time to do MANY raids, that know very well that boss with their classes, and would like to kill at 1st shoot, with other 9 people...probably will kill it...or not....with 8 people at least...so a content designed for 10 player will be done by 9 player, with noob one dead. He will just leech the LI, will do not understand NOTHING of that raid, and he will just get LI with other LI. With your program, this only happends. Copy/paste chat code was difficult...and sometimes people did mistakes pressing Enter so they double paste...easy faker kick. With your Macro, layer could get a spot in a raid with a precise requirements (li/kp) and will give no possibility to other skilled player to play. It is not elitism. It is just the life. A baby doesnt go at university at his first day of school. After some years, if extraordinary, he could. To fake LI (and it is mainly what your program is used for) wastes the yet degraded raid experience.
There are many times "training raid"...people get their first kills in these ways. My first week, i did only the VG 10-15 times more or less. With just 1LI, I joined squad, write my message. In just 1 week, with just 1 LI, i had learnt all possible techniques to kill VG (hard core guild's strategies too) as dps. Next week I started as druid....other 3-5 time...and know I know all strategies to kill VG being dps or druid. I know also tanker stuff, but never tried, and I will never say in a 250li squad "i can go tank"...maybe "i could try" (but my experience like mesmer are very low :P so neither try atm).
So if you did your program to allow people to fake LI, wasting other 9 people time/game experience, please, delete it. If you did really as in your disclaimer, to not bring useless inventory slot wasted, please just add a message that link your program to people. So many other could even discover your program. But that to it, commander will know that MAYBE, if that player fail in raid (ex. running without reason in bomb at escort), he will be definetly a faker. Player with 250li, that has passed that hell, probably are allowed to look for other skilled player. Leave commander and squad freedom to decide to carry or not a probable faker.

I would also add to you and to all people that use your program at actual state of art:
This program goes against rules of ArenaNet and ALL users are probably eligible for account ban!
Link: https://en-forum.guildwars2.com/discussion/352/policy-third-party-programs-multi-boxing-macros#latest

"Does this program allow someone to play faster, better, longer, or more accurately than someone who doesn't use it?"
"If you choose to use what you believe to be a "benign" program—one that does not give an advantage to the user"
Yes, it does. Your program at actual state of art, allowes player to fake LI, and get squad slot to people with not skills/experience wasting and degrading other player's experience. More over, it allowes player with no experience to take the slot instead of another "real eligible" player.

"If you program a macro, it must require one keystroke per action. You may not program a single key to perform multiple functions. For example, if you Press A and it results in the casting of a single skill, you're ok. If you Press A and it casts multiple spells, you're not ok."
I have seen program on videos. Your program, clicking 1 button, press simultaneously 2 button (ctrl+v) and next "enter", so this is a combination of buttons, and it is not allowed by rules.

You are releasing a program without warning users that using it they are eligible for ban.

So please. i really appreciate your intention as developer, but if you would like to keep online this program, add at least a declination of responsibility warning user about the rules breaking, and put a link to this repository so that commander are allowed to check and are free to decide what to do with people that use your program.

I reapeat myself. Im not a elitist. I allow many times 1 (2max) people with no experience/li/kp to join my group if they tell me. So they learn and get they li/kp. Im just telling this cause I cant decide who carry, who not, but im totally in hand of "i do neither know what" :P

Thx dev!

**Comment by quetzalsly** [comment]
This tool is ideal for me because I actually had an account on a different region with 250 li but then moved to a different country and made a new account. Not everyone has sinister intentions using this tool.

**Comment by DoctorD90** [comment]
Sure, for this adding a simple "watermarker" could easly help people like you :)
It is totally easy see if a person has a certain level of experience or not :)
But at least it would help other 9 people to play and enjoy the game playing with you and you could not bring LI in inventory.
Adding a "watermarker" it could also help to spread the knowledge about this program.
