### ISSUE TITLE
W6 Qadim kill proof

### ISSUE THREAD

**Issue by SanderWasser** [m10x/Gw2ChatCodeBuddy#8]
Hee,

Love your tool, it realy makes raiding less elitist and more accesable for new players.
Have been using it for a long time and now close to 250 Li.
But recently i noticed that the kill proof of Qadim W6 is not working for me.
What i do in the program is:
1 (for shortcut)
2 (for wings)
6 (for W6)
3 (for Qadim)
And then it just does noting and resets.
Can you replicate this error, or am i doing something wrong ?

I tried to find the problem and noticed that the largos gold trophy also does't work for me.
When i type in the amout, it always goes back to asking what KP i want from W6.

kind regards,
Sander

**Comment by Heycate** [comment]
Does't work for me too
Select Qadim, and i came back to the start

**Comment by Griftnix** [comment]
Hello to solve this issue  go to file:
Gw2ChatCodeBuddy.py
Line 406 and 407 it says:
elif inputUser == 3:
                                assign_button(button, "Qadim KP", "[&AgFFWgEA]")

you have to delete the indent in front of "elif inputUser == 3:" until it is in line with line 387
"elif inputUser == 2:"

it seems, too many indents were made.

**Comment by Heycate** [comment]
Hello where is this file ?

**Comment by TanguyMrtn** [comment]
I fixed it, but when I build the .exe I get a 47mb exe file, too large ! (I don't know how I can get a 7mb exe, feel free to tell me if you know how to decrease the exe file size)

**Comment by m10x** [comment]
I'm sorry for taking so long. New version with the fix ist uploading atm! Feel free to make merge requests if you fix something etc. I also uploaded a tutorial how you can create the exe yourself :)

**Comment by m10x** [comment]
fixed :)
