### ISSUE TITLE
Changing 'p' to pause

### ISSUE THREAD

**Issue by BadRaider** [m10x/Gw2ChatCodeBuddy#9]
Hello, I'd really like to change the 'p' global config to pause as of right now I can't type /p to talk in party or say "hello dps" before spamming. I tried looking in the code but I don't understand most of the code so I'm stuck here.
Could you change it in the next release or tell me which part of the code I should modify to assign the functions currently associated with 'p' to another key like '*' for example.

**Comment by BadRaider** [comment]
Update, I found the part of the code, the end of Gw2ChatCodeBuddy.py, I changed the VK_P to VK_N (could I use "VK_*"?) but now, I can't set up a python environment and successfully use pyinstaller... mos tof this doesn't make much sense to me, help would be much appreciated.

**Comment by m10x** [comment]
I will create a tutorial on how to setup up python, pyinstaller etc. to create a exe. I could maybe do a button which one could assign which puts the whole program to standby, so you can press Every button, besides the standby button

**Comment by BadRaider** [comment]
Thank you very much :+1:

**Comment by m10x** [comment]
I'm sorry for taking so long, I made a tutorial how you can create the exe yourself. Take a look at the newest release, which also contains bugfixes.
